language: groovy

jdk:
  - oraclejdk8

after_success:
  - build-scripts/deploy_snapshot.sh

env:
  global:
    - secure: "hbdUw300E3idl/lHpmprXXNXK5D+BFP5waNouQDrHjhp1pl+yKFq82qCUtSBe5ushk5Nj8jbV1/IPlWqiut0Y+fGo58dSNxFwWvhBhZy3AzbfqVgL2lrV9jT8FP+udrFiAwfVz6D/kjzxmD42vMtQK+AezIfU3r6BYdJE9fXnZE="
    - secure: "bupzjXKdJTO7s5N72lc7LJfYZA4ZZn+VpXBnHiCSw+Nwa8ISX6VOAlh6+ZfAX++moCzAIAmgN3a3AgPfClosxkYuD5q6v0DOwka+JIGFQMAe4FcnrKbVVQpmorE8GgwAWsZ9BBMqNiL5ofWBLHHaTnB+nB7Rn8P/g3lgKVml004="

cache:
  directories:
    - $HOME/.gradle
